baseURL = 'https://xr0814.github.io/hugonews/'
languageCode = 'en-us'
title = '文文家的小可爱'
theme = 'ananke'
publishDir = "docs"

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true